[tool.poetry]
name = "kanoon"
version = "0.1.0-alpha.1"
description = ""
authors = ["Nihal Sahu <iamnihalsahu@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pypdf = "^3.16.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
